version: '3.7'
services:
        frontend:
          container_name: fe
          image: sigit26/dumbflix-fe:1.0
          stdin_open: true
          ports:
            -  "3000:3000"

        frontendloadbalance:
          container_name: feloadbalance
          image: sigit26/dumbflix-fe:1.0
          stdin_open: true
          ports:
            -  "3001:3001"
